### PR TITLE
Add new setting for split bar size.

### PR DESCRIPTION
**Pull request by ipankajg**
Add a new option in styles setting page for split bar size in pixels.
The split bar size is then used for both horizontal and vertical split.
This allows user to override default value of 4px and use custom range
from 1-8px.

### CODE REVIEW

**Comment by ipankajg** [comment]
This option makes it easier to have a very thin split-bar like 1px similar to TMUX. The default is kept at 4px as earlier so no change in behavior if this option is not set or set to 0.

**Comment by ipankajg** [comment]
Adding two screenshots for reference. First shows the settings page change and second shows difference between 1px split vs default 4px split.
consolez_splitbarsize
consolez_thinsplit

**Comment by cbucher** [comment]
Thx

**Comment by ipankajg** [comment]
Thank you for merging the change!

**Pull request merged**
