### PR TITLE
Dpi awareness

### PR DESCRIPTION
**Pull request by gfody**
I merged the fixups from gfody-dpi-awareness and also got setting the dpi-awareness at runtime to work (it has to be called before any other winapi that uses dpi-awareness, and it cannot be specified in the manifest). So now it's controlled by fontSettings.dwDpiAwareness, defaults to "system aware", and shouldn't bother systems without shcore.dll

### CODE REVIEW

**Comment by gfody** [comment]
added the option to Appearance/Font..

settings

**Comment by cbucher** [comment]
For now, I do not put a configuration option. The previous version was already DPI aware and nobody complained. No reason to have fuzzy fonts and icons :wink:
*At least I hope no one will create an issue because he prefer a blur font...*

So we will wait for feed backs.

However this setting should not be classed in font settings but in styles settings (because that modifies the window composition and not only the console view font) and font settings could be handled per tab in the future.

**Comment by gfody** [comment]
People with high DPI primary display and low DPI secondary (extended desktop to a projector or tv) may prefer the system aware setting over per-monitor to avoid the oversized toolbar, menu and titlebar problem when the system not scaling those things down. People with low DPI primary display and high DPI secondary (like me - extended desktop onto retina laptop display) may still prefer the system setting if the blurry fonts bother them less than the tiny toolbar, menu and titlebar.

You're right I cannot think of any reason someone would choose "DPI Unaware" though. So perhaps this option should just be a checkbox. I'll revert the combo and add a checkbox to the Style dialog.

**Comment by gfody** [comment]
settings

**Pull request merged**
