### PR TITLE
Fix XP build

### PR DESCRIPTION
**Pull request by native-api**
Fixed "Release Legacy" and "Debug Legacy" to produce XP-compatible output.

### CODE REVIEW

**Comment by Saibamen** [comment]
Why?

**Comment by native-api** [comment]
There are "Debug Legacy" and "Release Legacy" configurations to build for XP. Presently, they don't produce an XP-compatible output. The patch fixes that.
If XP support is officially dropped, these configurations need to be dropped, too, to avoid giving a false impression.

**Comment by cbucher** [comment]
irrelevant for **packaging** project : this makefile project does not use the SDK
irrelevant for **help** project : this makefile project does not use the SDK
irrelevant for **l10n** project : this makefile project build resource only dlls

**consoleWow** is only used on 64 bit OS.

**Comment by native-api** [comment]
> irrelevant for packaging project : this makefile project does not use the SDK
> irrelevant for help project : this makefile project does not use the SDK

Then the current `v141` references are just as irrelevant. Sure, can delete them instead.

> irrelevant for l10n project : this makefile project build resource only dlls

Every DLL has a "Minimum OS version" and "Minimum subsystem version" fields in PE optional header. `v141` sets them to `6.00`, and the DLL won't load in XP.

Addressed these in https://github.com/native-api/console/commit/e51059131f0e962250b03cd19bd41f68de6bedc7 .

**Comment by cbucher** [comment]
>Every DLL has a "Minimum OS version" and "Minimum subsystem version" fields in PE optional header. v141 sets them to 6.00, and the DLL won't load in XP.

Verify before writing...
image
Localization dlls are loaded only as data file (LOAD_LIBRARY_AS_DATAFILE), no code is executed. That's why we use the same dlls in 32 and 64 bits.

"Minimum OS version" and "Minimum subsystem version" fields in PE optional header are only checked for executables.
image
If a dll built with `v141` (instead of `v141_xp`)  cannot be loaded on XP, it is because dependencies are missing.
Otherwise FreeImagePlus.dll would not load in XP.
```
>dumpbin.exe /HEADERS "C:\gitstuff\console.git\bin\Win32\Release Legacy\FreeImagePlus.dll"
Microsoft (R) COFF/PE Dumper Version 14.13.26132.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\gitstuff\console.git\bin\Win32\Release Legacy\FreeImagePlus.dll

PE signature found

File Type: DLL

FILE HEADER VALUES
             14C machine (x86)
               8 number of sections
        56FC2317 time date stamp Wed Mar 30 21:03:51 2016
               0 file pointer to symbol table
               0 number of symbols
              E0 size of optional header
            2102 characteristics
                   Executable
                   32 bit word machine
                   DLL

OPTIONAL HEADER VALUES
             10B magic # (PE32)
           14.00 linker version
          250600 size of code
          311200 size of initialized data
               0 size of uninitialized data
          1D6E6F entry point (101D6E6F)
            1000 base of code
          252000 base of data
        10000000 image base (10000000 to 10566FFF)
            1000 section alignment
             200 file alignment
            6.00 operating system version
            0.00 image version
            6.00 subsystem version
               0 Win32 version
          567000 size of image
             400 size of headers
               0 checksum
               2 subsystem (Windows GUI)
             100 DLL characteristics
                   NX compatible
          100000 size of stack reserve
            1000 size of stack commit
          100000 size of heap reserve
            1000 size of heap commit```

**Pull request closed without merging**
