### PR TITLE
Add Swap Split menu item

### PR DESCRIPTION
**Pull request by char101**
Add Swap Split menu item to the Edit menu. Only swap the top splitter currently; less useful for nested split but better than nothing though.

### CODE REVIEW

**Comment by cbucher** [comment]
thanks for your code

handling nested split should be easy
two ways:
- walk the tree to the node containing the active view and swap
- or split with a direction (split with the right/left/top or bottom view)

what is your opinion?

**Comment by char101** [comment]
Split with direction will be limited to adjacent panes. To generalize the swapping operation, I have added a new menuitem: Swap with Previous View. So the user first set focus (click) on the first pane, then set focus (click) on the second pane. After that s/he can swap those panes. I have renamed the previous Swap Split to Swap with Sibling Pane. Unlike Swap with Sibling Pane, Swap with Previous Pane will not swap the width/height so I keep them as separate menu items.

**Comment by cbucher** [comment]
image

close C (CTRL+SHIFT+W)

image

"Swap with previous Pane"

image

**Comment by cbucher** [comment]
multisplitClass internal state and tree should not be modified from Mainframe class.
If you want to extend capabilities of multisplitClass , you must add methods to this class.
So multisplitClass (with swap capabilities) can  be reused in other projects. And you can guarantee internal consistency (and prevent from previous crash).

I should have protect members and add getters.

**Comment by cbucher** [comment]
"Swap with sibling pane" : the title is false you swap only the root

image

The sibling pane of C is B. And nobody understand the following result (I made the test with three persons):

image

**Comment by cbucher** [comment]
@char101 Did you plan to fix?

**Comment by char101** [comment]
I don't have plan to fix it in the near time. C++ with Visual Studio is not my main area nor my hobby, so it is hard to work on these again after a while. If you plan to implement these feature, I think it is easier if you fix it yourself.

The first crash is easy to fix. The previous pane pointer has been obsolete since the pane has been removed, so we only need to check if it is valid.

About "Swap with sibling pane", B & C is actually wrapped in a splitter pane right? So the sibling pane of A is the parent of B & C. It is not "Swap with sibling console" but with "sibling pane".

**Pull request closed without merging**
