### PR TITLE
per-monitor dpi awareness

### PR DESCRIPTION
**Pull request by gfody**
Very basic per-monitor dpi awareness by handling WM_DPICHANGED and updating zoom by whatever factor the system used to resize the window. Looks much better than system scaled font, e.g:
compare

[Good msdn overview of per-mon-dpi awareness](https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266%28v=vs.85%29.aspx)

### CODE REVIEW

**Comment by gfody** [comment]
rebased to 1.15.0.15183, fixed problem when normal font and scaled font aren't evenly divisible

**Comment by gfody** [comment]
got rid of the zoom hack and properly incorporated dpi into ConsoleView::CreateFont

Few issues remain:
- if you move the window across a dpi boundary via ctrl+click (or whatever 'Drag Window' key) the window gets really messed up
- only ConsoleView font size is scaled, the system menu, toolbar, and status bar all appear tiny on the high dpi screen.
- some users may prefer the system scaling which is disabled once you register as per-monitor-dpi-aware. I tried setting it at runtime with SetProcessDpiAwareness but this didn't work on my system.

**Comment by cbucher** [comment]
> if you move the window across a dpi boundary via ctrl+click (or whatever 'Drag Window' key) the window gets really messed up

Yes I can see a loop problem:
```
WM_WINDOWPOSCHANGING (3385x236)-(0x0)
WM_WINDOWPOSCHANGING (3385x236)-(0x0)
WM_WINDOWPOSCHANGING (3411x236)-(0x0)
**************************************
MainFrame::OnDpiChanged (96)
**************************************
ConsoleView::CreateFont (96 dpi)
WM_DPICHANGED (3411x236)-(675x466)
WM_WINDOWPOSCHANGING (3411x236)-(675x466)
TabView::OnSize -> multisplitClass::RectSet
G:\gitstuff\console.git\wtl\wtl\include\multisplit.h(650) : atlTraceGeneral - CMultiSplitImpl::RectSet: 0 0 653 321 (653 321) from 0000000000000000
!!! ConsoleView::OnSize (2) !!!
G:\gitstuff\console.git\wtl\wtl\include\multisplit.h(313) : atlTraceGeneral - CMultiSplitPane::updateLayout: 0 0 (653 321)
**************************************
MainFrame::OnDpiChanged (144)
**************************************
ConsoleView::CreateFont (144 dpi)
WM_DPICHANGED (3411x236)-(1013x699)
WM_WINDOWPOSCHANGING (3411x236)-(1013x699)
TabView::OnSize -> multisplitClass::RectSet
G:\gitstuff\console.git\wtl\wtl\include\multisplit.h(650) : atlTraceGeneral - CMultiSplitImpl::RectSet: 0 0 991 554 (991 554) from 0000000000000000
!!! ConsoleView::OnSize (3) !!!
G:\gitstuff\console.git\wtl\wtl\include\multisplit.h(313) : atlTraceGeneral - CMultiSplitPane::updateLayout: 0 0 (991 554)
**************************************
MainFrame::OnDpiChanged (96)
**************************************
ConsoleView::CreateFont (96 dpi)
WM_DPICHANGED (3411x236)-(675x466)
WM_WINDOWPOSCHANGING (3411x236)-(675x466)
TabView::OnSize -> multisplitClass::RectSet
G:\gitstuff\console.git\wtl\wtl\include\multisplit.h(650) : atlTraceGeneral - CMultiSplitImpl::RectSet: 0 0 653 321 (653 321) from 0000000000000000
!!! ConsoleView::OnSize (4) !!!
G:\gitstuff\console.git\wtl\wtl\include\multisplit.h(313) : atlTraceGeneral - CMultiSplitPane::updateLayout: 0 0 (653 321)
**************************************
MainFrame::OnDpiChanged (144)
**************************************
ConsoleView::CreateFont (144 dpi)
WM_DPICHANGED (3411x236)-(1013x699)
WM_WINDOWPOSCHANGING (3411x236)-(1013x699)
TabView::OnSize -> multisplitClass::RectSet
G:\gitstuff\console.git\wtl\wtl\include\multisplit.h(650) : atlTraceGeneral - CMultiSplitImpl::RectSet: 0 0 991 554 (991 554) from 0000000000000000
!!! ConsoleView::OnSize (5) !!!
G:\gitstuff\console.git\wtl\wtl\include\multisplit.h(313) : atlTraceGeneral - CMultiSplitPane::updateLayout: 0 0 (991 554)
**************************************
MainFrame::OnDpiChanged (96)
**************************************
ConsoleView::CreateFont (96 dpi)
WM_DPICHANGED (3411x236)-(675x466)
WM_WINDOWPOSCHANGING (3411x236)-(675x466)
TabView::OnSize -> multisplitClass::RectSet
G:\gitstuff\console.git\wtl\wtl\include\multisplit.h(650) : atlTraceGeneral - CMultiSplitImpl::RectSet: 0 0 653 321 (653 321) from 0000000000000000
!!! ConsoleView::OnSize (6) !!!
G:\gitstuff\console.git\wtl\wtl\include\multisplit.h(313) : atlTraceGeneral - CMultiSplitPane::updateLayout: 0 0 (653 321)
**************************************
MainFrame::OnDpiChanged (144)
**************************************
ConsoleView::CreateFont (144 dpi)
WM_DPICHANGED (3411x236)-(1013x699)
WM_WINDOWPOSCHANGING (3411x236)-(1013x699)
TabView::OnSize -> multisplitClass::RectSet
G:\gitstuff\console.git\wtl\wtl\include\multisplit.h(650) : atlTraceGeneral - CMultiSplitImpl::RectSet: 0 0 991 554 (991 554) from 0000000000000000
!!! ConsoleView::OnSize (7) !!!
G:\gitstuff\console.git\wtl\wtl\include\multisplit.h(313) : atlTraceGeneral - CMultiSplitPane::updateLayout: 0 0 (991 554)
**************************************
MainFrame::OnDpiChanged (96)
**************************************
ConsoleView::CreateFont (96 dpi)
WM_DPICHANGED (3411x236)-(675x466)
WM_WINDOWPOSCHANGING (3411x236)-(675x466)
TabView::OnSize -> multisplitClass::RectSet
G:\gitstuff\console.git\wtl\wtl\include\multisplit.h(650) : atlTraceGeneral - CMultiSplitImpl::RectSet: 0 0 653 321 (653 321) from 0000000000000000
!!! ConsoleView::OnSize (8) !!!
G:\gitstuff\console.git\wtl\wtl\include\multisplit.h(313) : atlTraceGeneral - CMultiSplitPane::updateLayout: 0 0 (653 321)
```

x <= 3839 we are in 144 dpi monitor
x > 3839  we are in 96 dpi monitor

We are in 144 dpi monitor.
- We enter into 96 dpi monitor, 
- then the window is reduced. x = 3411 and cx = 675 --> 428 pixels on 144 dpi monitor and 247 pixels on 96 dpi monitor
- With the new size, we enter into the 144 dpi monitor.
- then the window is expanded. x = 3411 and cx = 1013 --> 428 pixels on 144 dpi monitor and 585 pixels on 96 dpi monitor
- With the new size, we enter into the 96 dpi monitor.
- ...

>I tried setting it at runtime with SetProcessDpiAwareness but this didn't work on my system.

Documentation says:
This API fails if the DPI awareness is specified in the application manifest or if this API has been called previously.
You must call this API before you call any APIs that involve a monitor’s coordinate space.

**Comment by cbucher** [comment]
@gfody can you post a picture comparing current release version of ConsoleZ (which supports High DPI) with your modified version of ConsoleZ (which supports High DPI Per Monitor).
In your previous picture, I can see the old version of Console2 and a non specified version of ConsoleZ (High DPI or High DPI Per Monitor ?).

**Comment by gfody** [comment]
I think this will take care of the ctrl-click issue - using OnMouseMove for that was kind of janky. This way the system is doing it and so it behaves the same as if you were dragging my the title bar (gestures work, snapping to the sides, etc.)

I won't be able to take new screen shots until next week when I have access to the high dpi monitor again. I had already replaced my ConsoleZ binary when I was grabbing that screenie so I used Console2 which I had installed separately but looks exactly the same. High dpi support doesn't necessarily change how everything appears when the system has scaled it up in the case of your primary monitor being low dpi and your secondary monitor being high dpi. If your primary monitor is high dpi and the secondary monitor is low then the system will scale it down giving a different but similarly unpleasant effect of slightly blurring fonts. There is a good overall summary of how it works here: https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266%28v=vs.85%29.aspx

In my office we all have two normal screens and one retina display and we've found that we have to set our primary monitor to be one of the normal screens or most applications in Windows will look terrible as they're being first rendered in high dpi (which sometimes throws controls out of place) and then scaled down which makes all the text blurry.

**Comment by gfody** [comment]
Below are some tests showing how the per-mon-dpi build and the high-dpi build look in the different scenarios,

on primary 96dpi, both builds look identical
normal_96

moved high-dpi build from primary (96) to secondary (192)
system scales everything up, fonts look terrible (except for the window chrome which looks fine)
high_96

moved per-mon-dpi build from primary (96) to secondary (192)
console font is crisp but the toolbar, menu, status bar, and window chrome appear small as the system does not scale them for us
per-mon_96

on primary 192dpi, both builds look identical
normal_192

moved high-dpi build from primary (192) to secondary (96)
fonts are blurred as the system scales everything down
high_192

moved per-mon-dpi build from primary (192) to secondary (96)
fonts are crisp but the toolbar, menu, status bar, and window chrome appear large as the system does not scale them down for us (included a regular explorer window for comparison)
per_192

Ideally the per-mon-dpi build would recreate the menu, toolbar, and status bar with the appropriate sized font and graphics when handling WM_DPICHANGED.

**Comment by gfody** [comment]
rebased

**Comment by cbucher** [comment]
I will try that.
I don't have any special monitors, so I can only set a maladjusted DPI.
But theoretically, the rendering should have a looking in any case.

**Comment by cbucher** [comment]
Nice

I just have a question: why the limitation to Win64 only?

My test result:
when I pass from 144 dpi to 96 dpi, the number of rows/lines is modified
chars to the right disappear, can you fix this?

image

image

**Comment by cbucher** [comment]
integrated and modified in last experimental version

That will be merged in master branch if no issue is reported.

I attempt to resize other elements.
I can modify the size of toolbar and status bar but not the menu.

**Pull request closed without merging**
