### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by ya158**

### CODE REVIEW

**Comment by cbucher** [comment]
Thank you for the translation.

**Comment by cbucher** [comment]
There are mismatches between translations in `.ini` file and strings in `.rc` file!

I explain again:
- you simply edit .ini file
- you update .rc file with LocateRC tool by clicking on "Create Output RC with INI"

https://github.com/cbucher/console/wiki/How-to-localize-ConsoleZ

**Comment by ya158** [comment]
If only edit the ini file, the normal dll not will be created. It is necessary not only to translate the phrases, but also change the size of the place where they are used.
For example:
In English
`RTEXT           "Split bar siz&e*:",IDC_STATIC,123,116,49,8`
In Russian
`RTEXT           "Толщина &границы разделения*:",IDC_STATIC,110,112,63,16`

I think that in general ini file is not needed - much easier and more accurate editing rc file. I always edit only the rc file, and then copy the translation in the ini file.
Please delete the ini file and let only translate rc file.

**Comment by cbucher** [comment]
>If only edit the ini file, the normal dll not will be created.

read carefully:

> you update .rc file with LocateRC tool by clicking on "Create Output RC with INI"

>I think that in general ini file is not needed - much easier and more accurate editing rc file. I always edit only the rc file, and then copy the translation in the ini file.

You are wrong, I update .ini file and .rc file every time I add a new string in resources.
you really think I will edit each rc file to add new strings?

>Please delete the ini file and let only translate rc file.

Without INI file, without my tool, bye bye simply edit strings that magically appear in RC file.!

**Comment by ya158** [comment]
I apologize for not having replied. I tried it before your LocalizeRC, but the resulting console.rc was incorrect. I had a long time to fix it, that would be fine strings appear. Maybe I'm wrong, but personally I find it easier just to edit only console.rc and immediately check it at ConsoleZ compilation.
I will edit ini, but do not know when I can update.

**Comment by cbucher** [comment]
>I find it easier just to edit only console.rc and immediately check it at ConsoleZ compilation.

It's easy to compare:

There is the final english resource file:
https://github.com/cbucher/console/raw/master/Console/Console.rc

And there is your previous russian resource file:
https://raw.githubusercontent.com/cbucher/console/82167a2762ded0186cbb99601664f3044b51d44c/l10n/RUS/console.rc

Attempt to synchronize your file and update the translation without my tool.
And say me, honestly, how much time you spent.

image

**Pull request merged**
