### PR TITLE
Session support

### PR DESCRIPTION
**Pull request by char101**
Basic session support using `boost::property_tree`.

Sample multitab session file

```
tabs
{
    0
    {
        title ConsoleZ
        isSplit false
        currentDirectory R:\\
    }
    1
    {
        title AAA
        isSplit true
        splitType 1
        splitRatio 50
        currentDirectory C:\\
        pane0
        {
            title AAA
            isSplit false
            currentDirectory C:\\
        }
        pane1
        {
            title AAA
            isSplit false
            currentDirectory D:\\
        }
    }
}
```

Sample deeply nested tab

```
tabs
{
    0
    {
        title ConsoleZ
        isSplit true
        splitType 1
        splitRatio 50
        currentDirectory D:\\Compile\\console\\console-char101
        pane0
        {
            title ConsoleZ
            isSplit false
            currentDirectory D:\\Compile\\console\\console-char101
        }
        pane1
        {
            title ConsoleZ
            isSplit true
            splitType 2
            splitRatio 50
            currentDirectory D:\\Compile\\console\\console-char101
            pane0
            {
                title ConsoleZ
                isSplit false
                currentDirectory D:\\Compile\\console\\console-char101
            }
            pane1
            {
                title ConsoleZ
                isSplit true
                splitType 1
                splitRatio 50
                currentDirectory D:\\Compile\\console\\console-char101
                pane0
                {
                    title ConsoleZ
                    isSplit false
                    currentDirectory D:\\Compile\\console\\console-char101
                }
                pane1
                {
                    title ConsoleZ
                    isSplit true
                    splitType 2
                    splitRatio 50
                    currentDirectory D:\\Compile\\console\\console-char101
                    pane0
                    {
                        title ConsoleZ
                        isSplit false
                        currentDirectory D:\\Compile\\console\\console-char101
                    }
                    pane1
                    {
                        title ConsoleZ
                        isSplit false
                        currentDirectory D:\\Compile\\console\\console-char101
                    }
                }
            }
        }
    }
}
```

Reference: #127

### CODE REVIEW

**Comment by char101** [comment]
Added auto save/auto load session file. The file will be stored in the same folder as console.xml.

**Comment by DerellLicht** [comment]
Is this feature included in release branch??  
I *desperately* want ability to save/restore sessions...

**Comment by char101** [comment]
You can compile the application yourself or use the test executable here

https://github.com/char101/console/releases/tag/1.8.0.1

**Comment by DerellLicht** [comment]
hmmm... unfortunately, when I use this version, the keyboard does not 
work at all!!
I type in a console, nothing appears, but then if I switch to another 
tab and then back, what I had typed previously now appears on the 
command line, but any further typing does not appear...

My main installation is 1.15.0.15230 ; should your console.exe (V1.15) 
work with this distribution??

My consoles are all tcc/le 13.06.77
Windows 7 64-bit

On 09/17/15 18:09, Charles wrote:
>
> You can compile the application yourself or use the test executable here
>
> https://github.com/char101/console/releases/tag/1.8.0.1
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cbucher/console/pull/260#issuecomment-141299415>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by char101** [comment]
Typing works fine in my computer. I have updated `Console.7z` with the rest of the dlls/exes. I don't use TCC/LE though.

**Comment by DerellLicht** [comment]
Well, damn... no, still doesn't work, even with full package (I had to 
copy ConsoleHook32.dll from the original, in order to load it).
Just no keyboard at all.  Interestingly, cmd.exe works fine.

tcc/le is a free program:
https://jpsoft.com/downloads/v14/tccle.exe

Is there any chance you might consider trying it with your version??  I 
would *really* love to have save-session available to me, especially at 
work where I have to open 7 or more consoles in ConsoleZ, every time I 
have to reboot...


On 09/17/15 20:46, Charles wrote:
>
> Typing works fine in my computer. I have updated |Console.7z| with the 
> rest of the dlls/exes. I don't use TCC/LE though.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cbucher/console/pull/260#issuecomment-141335616>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by DerellLicht** [comment]
Second question; is there some way I can pass sessions.czs on command, preferably in my taskbar launcher??  It is good the way as it is, but this would be more efficient...

**Comment by char101** [comment]
There is an auto load/auto save session in the preference dialog.

**Comment by DerellLicht** [comment]
Wow.... and it works perfectly, too!!  Thank you so much!!!

**Comment by DerellLicht** [comment]
BTW, if you *do* wish to test tcc/le 32-bit on your version, it's a free program:
https://jpsoft.com/downloads/v14/tccle.exe

**Comment by char101** [comment]
I'm using TCC/LE now (64 bit) as my `cmd.exe` replacement. Pretty cool replacement :+1:, I like the builtin which command and alias support. Thanks.

**Comment by DerellLicht** [comment]
Okay, I'm definitely sold... today was sooooo much smoother at work!!  I have to reboot fairly regularly at work (for reasons that aren't relevant to anything here), and the agonizing procedure to get all my (typically 8 or 9) consoles opened, CD'd, and renamed, was becoming very trying...  until now... so cool!!! 

The only thing missing now is Aero theme... it's not important enough to ask for a special build, but I'd like to know what your plans are for getting your branch integrated into release branch??  (I'm familiar with Git).  I would *love* to see this in the mainstream, and never again have to worry about losing it!!

**Comment by cbucher** [comment]
A specification of *workspace* is going on here #274.

**Comment by DerellLicht** [comment]
Hi cbucher!  
I am unclear what the significance of your previous comment is... are you reluctant to use char101's revision to the project?   

I understand the concept behind wanting a spec before working on something, but nevertheless this mod appears to be working very well... (though I haven't looked at split-tab operation, which I don't use).

**Comment by DerellLicht** [comment]
I *have* been experiencing one issue with this build.  If ConsoleZ.sessions is running, and has had new consoles opened in this session, when the computer is rebooted, then after the reboot, ConsoleZ will not successfully run at all!!  

To restore my session, I have to restore from my original working session.  My guess is that I could restore only console.czs and console.xml, but haven't experimented with it that much, have only rebooted a couple of times since switching to this version.

**Comment by leendek** [comment]
I tried this fix, but I get crashes every time I try to save a session that contains vertical splits.

**Comment by devicenul** [comment]
I just came looking for this. Is this dead? I'd love some sort of session or workspace (as mentioned above) support to be able to bring up tabs automatically laid out and connected as it was before.

**Comment by cbucher** [comment]
#274 support is available in workspace branch

**Pull request closed without merging**
